### ISSUE TITLE
TODO - Create the API call for getting Recipe Data.

### ISSUE THREAD

**Issue by MichaelWrobelPersonal** [kbeeler/Chef-s_Cabinet#2]
I believe Kevin indicated he has a start on this, just adding a note to make sure it is identified as needing to get done.

**Comment by MichaelWrobelPersonal** [comment]
A proposed function for performing searches using the Food API.

function searchRecipeAPI( SearchTerm ) {

// Code to use the Food API by spoonacular.com goes here

  for (var i=0; i<25; i++)
{
      // Code to fill in the itemsArray goes here
}

// 
    return itemsArray;  // An array of standard info representing the search results,
                                     // note: number of items can be determined from the array itself.
                                     // note: each Array entry will consist of a object containing the data 
                                    //            returned for the FoodAPI as used/needed by the website, it 
                                    //            only needs to contain info we will be using.
}

As we build out the web-site I anticipate we will need to expand what is returned in each item in itemsArray, Lets start its definition by the information that we need such as:

1) **Image** Url of the image of the searched for item
2) **Title** of searched for item (note can be used in follow-up searches) (text)
3) **Video** Url Link of video (text)
4) **Recipe** - Recipe text (text)
5) **Nutritional info** - Nutrition info (text)

As we add functionality lets expand/modify this object as needed.
Any methods for handling the data should be in the object.
Lets call the object itself searchItem and have it defined as follows:

let searchItem = {
title:    'Title',
image: 'url(#)',
video: 'url(#)',
recipe: 'recipe for success - TBD',
nutrition: 'very good for you'
}

the searchItems array will consist of zero or more searchItem objects.

**Comment by MichaelWrobelPersonal** [comment]
A sample of data from Kevin's code he has so far....
Should give us an idea of what we can do with the data, biggest take-away is that on clicking an image, we can get redirected to a site that has the recipe itself (see source_url field). Also publisher/publisher website fields may be useful.

{
"count": 30,
"recipes": [
{
"publisher": "The Pioneer Woman",
"f2f_url": "http://food2fork.com/view/7d8e83",
"title": "Breakfast Quesdillas",
"source_url": "http://thepioneerwoman.com/cooking/2013/04/breakfast-quesadillas/",
"recipe_id": "7d8e83",
"image_url": "http://static.food2fork.com/breakfastquesadilladc70.jpg",
"social_rank": 99.99999999712918,
"publisher_url": "http://thepioneerwoman.com"
},
{
"publisher": "Closet Cooking",
"f2f_url": "http://food2fork.com/view/35097",
"title": "Avocado Breakfast Pizza with Fried Egg",
"source_url": "http://www.closetcooking.com/2012/07/avocado-breakfast-pizza-with-fried-egg.html",
"recipe_id": "35097",
"image_url": "http://static.food2fork.com/Avocado2Band2BFried2BEgg2BBreakfast2BPizza2B5002B296294dcea8a.jpg",
"social_rank": 99.99999990783806,
"publisher_url": "http://closetcooking.com"
},

// Deleted intervening entries for brevity

{
"publisher": "Elana's Pantry",
"f2f_url": "http://food2fork.com/view/d80b1b",
"title": "Breakfast Power Smoothie",
"source_url": "http://www.elanaspantry.com/breakfast-power-smoothie/",
"recipe_id": "d80b1b",
"image_url": "http://static.food2fork.com/breakfastpowersmoothie529591c6.jpg",
"social_rank": 99.87248490739705,
"publisher_url": "http://www.elanaspantry.com"
}
]
}

**Comment by mkondray** [comment]
Done and done.  I made the API search into a function — searchRecipes(). Call it anytime ;)
